feat: add export_config input
scaleway/action-scw pull request #4
Opened 2023-04-17 09:22 UTC by Codelax

2023-04-17 16:00 UTC, quantumsheep requested changes

2023-04-17 17:09 UTC, Codelax commented on src/main.ts
> +    core.getBooleanInput('export_config') || defaultArgs.exportConfig,
getInput result cannot be null or undefined

2023-04-17 17:18 UTC, Codelax commented on src/config.ts
> +    `send-telemetry=false`,
Telemetry is unused in the CLI

2023-04-17 17:21 UTC, quantumsheep requested changes

2023-04-17 17:21 UTC, quantumsheep commented on src/main.ts
> +    core.getBooleanInput('export-config') || defaultArgs.exportConfig,
Use `??`

2023-04-18 07:47 UTC, Vinzius commented on src/config.ts
> +  ].join(' ')
Il ne pas y avoir un problème avec ce séparateur si une des variables contient un espace ? (cela ne devrait pas, mais cela arrivera surement :p)

2023-04-18 07:47 UTC, Vinzius commented on src/config.ts
> +  defaultOrganizationID: process.env.SCW_DEFAULT_ORGANIZATION_ID ?? '',
nit: je conseillerais plutôt d'avoir `string | undefined` en type plutôt que de fallback sur une string vide (qui fait plus Go like).

2023-04-18 07:47 UTC, Vinzius commented on src/main.ts
> +    core.getBooleanInput('export-config') || defaultArgs.exportConfig,
> The OR operator || uses the right value if left is [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy), while the nullish coalescing operator ?? uses the right value if left is null or undefined.

Si on veut pouvoir fallback sur la valeur suivante dans le dans d'une string vide, le `||` me semble adapté.

Je ne suis pas super fan, mais dans la logique cela fera le travail :)

2023-04-18 07:53 UTC, Codelax commented on src/config.ts
> +  defaultOrganizationID: process.env.SCW_DEFAULT_ORGANIZATION_ID ?? '',
Le typage est du à `core.getInput` qui renvoit `string` peu importe la présence ou non du la variable

2023-04-18 08:14 UTC, quantumsheep commented on src/main.ts
> +    core.getBooleanInput('export-config') || defaultArgs.exportConfig,
À vrai dire pour certains inputs il faudrait ne rien mettre, [getBooleanInput](https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/core/src/core.ts#L173) par exemple renvoie `true` ou `false` sans notion de "valeur non présente" et [getInput](https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/core/src/core.ts#L126) renvoie un erreur si aucune valeur est passée.

2023-04-19 07:32 UTC, Vinzius approved these changes

2023-04-19 08:03 UTC, quantumsheep approved these changes

2023-04-19 08:42 UTC, merged